services:
    webapi:
        build:
            context: .
            dockerfile: Dockerfile
        image: webapi_postgresql_v1
        ports:
        - "8080:8080"
        environment:
        - ASPNETCORE_URLS=http://+:8080
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionsStrings__DefaultConnection=Server=postgres;Port=5432;Database=postgres;Username=postgres;Password=123
        depends_on:
            - postgres        
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
        ports:
        - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
networks:
    default:
        name: my_custom_network
volumes:
    pgdata: